server:
  port: 9709
  servlet:
    context-path: /Burrow
  tomcat:
    accept-count: 50
  compression:
    enabled: true
    min-response-size: 2048
    
spring:
  application:
    name: BurrowNest
  datasource:
#    url: jdbc:h2:file:./data/burrownest.h2;AUTO_SERVER=TRUE
#    driver-class-name: org.h2.Driver
    url: jdbc:log4jdbc:h2:file:./data/burrownest.h2;AUTO_SERVER=TRUE
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: BurrowDbAgent
    password: qwer
    dbcp2:
      validation-query: SELECT 1
    hikari:
      auto-commit: false
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 120000
      max-lifetime: 600000
      connection-timeout: 15000
  h2:
    console:
      enabled: true
      path: /DbConsoleH2
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    user:
      name: admin
      password: my#9709
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cache.type: caffeine
caffeine.spec: maximumSize=100,expireAfterAccess=7d
      
      
jwt:
  secret: f4e42d85-73b0-4884-913f-f88ad661a1cc

security:
  pwSaltKey: Pa57242N708B7WO5U